default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "hiroto") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "yohi1208Qiut22") %>
  host: <%= ENV.fetch("MYSQL_HOST", "gds_db") %>

development:
  <<: *default
  database: gds_database

test:
  <<: *default
  database: gds_database

production:
  <<: *default
  database: gds_database
  username: hiroto
  password: <%= ENV['WEB_DATABASE_PASSWORD'] %>
