default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "gds_db") %>
  port: 3306

development:
  <<: *default
  database: gds_database_development

test:
  <<: *default
  database: gds_database_test

production:
  <<: *default
  database: gds_database_production
  username: hiroto
  password: <%= ENV['WEB_DATABASE_PASSWORD'] %>
